server {
    listen 80;
    index index.html;
    index index.html;

    client_max_body_size 20M;
    server_tokens off;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $http_host;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $http_host;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        root /static;
        try_files $uri $uri/ /index.html;
    }
}